readme.md, src/Faker/Factory.php, src/Faker/Generator.php, src/Faker/Provider/Biased.php, test/Faker/Provider/BiasedTest.php
biasedInteger allows generating an integer that is biased by a given function.
See fzaninotto/Faker#304
See this example data:
Number	|unbiased|	linearLow|	linearHigh|	sqrt	|square
-------------|------------|------------------|-------------------|------------|---------
1	|9857	|19016|	1007	|3222|	84
2	|10032	|17000|	2931	|5715|	717
3|	9966	|14977|	4928	|7538|	1846
4|	9914	|13015|	7033	|8872|	3645
5|	10099	|11080|	9145	|9915|	6095
6|	9800	|9012	|11001|	11234|	9138
7|	9987	|6860	|12936|	11906|	12800
8|	10096	|5053	|15047|	13160|	17019
9|	10026	|2945	|16919|	13775|	21512
10|	10223	|1042	|19053|	14663|	27144					
Loop iterations:	|100000|	200217|	199822	|150115|	299345
Loop iterations (percent)	|100.00%|	200.22%	|199.82%|	150.12%	|299.34%
Loop iterations are the number of times the contents …
=> Biased integer

readme.md, src/Faker/Provider/Image.php, test/Faker/Provider/ImageTest.php
Fixes the imageUrl provider bug when displaying several images on a web page.
Supersedes #372
=> add random GET argument for imageUrl faker

src/Faker/Provider/en_GB/Person.php
I've recently found myself using Faker for some test data to provide a demonstration system and found that the names which were being generated in most cases, weren't names which are commonly used in the UK.
I've created a simple Person class for the UK.
Data for forenames came from ONS [female names here](http://www.ons.gov.uk/ons/rel/vsob1/baby-names--england-and-wales/2013/info-girls-names-2013.html) and [male names here](http://www.ons.gov.uk/ons/rel/vsob1/baby-names--england-and-wales/2013/info-boys-names-2013.html) - I used the data from 2003 and 2013.
I also used some of the names already in the en_US locale which were relevant to a UK audience.
For surnames, I found a list [here](http://surname.sofeminine.co.uk/w/surnames/most-common-surnames-in-great-britain.html) which seemed to …
=> en_GB people provider

src/Faker/Provider/en_GB/PhoneNumber.php, src/Faker/Provider/en_NZ/PhoneNumber.php
Additions to the PhoneNumber Provider for en_GB so that a UK format phone number can be returned.
=> Addition of en_GB mobileNumber methods

readme.md, src/Faker/Generator.php, src/Faker/Provider/at_AT/Payment.php, test/Faker/Provider/at_AT/PaymentTest.php
=> +1 per-country VAT number, for at_AT

src/Faker/UniqueGenerator.php
Hi,
Currently the unique generator keeps the already used elements as array values and performs the lookup with `in_array` to assert that the generated value has not already been used. This operation is a O(n) operation which becomes slower in time for large datasets generation.
I refactored this operation to uses array indexes instead, which will leads to hash table lookups that are O(1) operations.
I did a little benchmark generating 10k unixTimes, the generation time is decreased from 1.77 seconds to 0.37 seconds.
=> Improve unique generator performance

src/Faker/Provider/Miscellaneous.php, test/Faker/Provider/MiscellaneousTest.php
Created faker for currency codes (similar to country codes and language codes). The list of currencies are taken from the ISO 4217 standard list.
=> Created faker for Currency Codes.

src/Faker/Provider/es_AR/Address.php
CitySuffix should be separated by a space from the name.
The building number should be after the street name.
=> Updated es_AR Address.php provider

readme.md
changed to http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/
Thanks to derecho.elijah.cs.cmu.edu:8585/@top
=> Fixed broken Doctrin2 link

src/Faker/Generator.php, src/Faker/Provider/Base.php, src/Faker/Provider/DateTime.php, src/Faker/Provider/File.php, src/Faker/Provider/Lorem.php, src/Faker/Provider/Miscellaneous.php, src/Faker/Provider/Payment.php, src/Faker/Provider/Person.php
This adds missing magic methods in the Generator for new providers and adds arguments for methods to avoid warnings about unused arguments when using them.
It also fixes a few return types to be consistent with the implementation.
=> Update the phpdoc for magic methods

src/Faker/Provider/nl_NL/Person.php
This also caused the creation of invalid mailaddresses
=> Wrong use of ’. It should be '

src/Faker/Provider/File.php
This is a fix for the issue #539. Directories are excluded using the provided filter.
=> Fix for 'The first argument to copy() function cannot be a directory'

src/Faker/Provider/File.php
After fixing #547 I found out that there are some other cases which will cause ```copy``` to fail: unreadable files and special files (e.g. pipes).
The proposed changes should fix this issue and additionally I added an exception if the chosen directory is empty.
=> Fixed file provider to ignore unreadable and special files

src/Faker/Provider/fr_FR/PhoneNumber.php
Adding function for generating french mobile phone number in fr_FR provider
=> Add mobile phone function in fr_FR provider

src/Faker/Calculator/Iban.php, src/Faker/Provider/Payment.php, test/Faker/Calculator/IbanTest.php, test/Faker/Provider/PaymentTest.php
This fixes:
* IBAN formats for Kuwait and Turkey (source: http://www.swift.com/dsp/resources/documents/IBAN_Registry.pdf)
* Checksum calculation for IBANs with letters
* Off by one error in format boundaries
=> Fix IBAN generator

readme.md
I found it really hard to get around the readme to answer my questions quickly. I wasn't familiar enough with it to search for what I needed. To that end, I created a readme file to go with it.
Let me know if there are any changes you want me to make. Great library, btw, I'm really enjoying using it.
=> Adds a table of contents to the readme file.

readme.md, src/Faker/Provider/DateTime.php, test/Faker/Provider/DateTimeTest.php
Permit to take a date and add or substract a php recognized interval.
I'm sure this can be usefull, because i write that in one of my alice loader, but not if this can be look as good writed (long in comparison with other pretty date functions) or in your waited tasks list.
So let me know if you want i finish with csfixer, tests, rebase and all or if this is not usefull.
@see http://php.net/manual/fr/dateinterval.createfromdatestring.php
@see http://php.net/manual/fr/datetime.formats.relative.php
@note : edited directly on github for moment
=> Feature : Add dateTimeInInterval Method

.travis.yml, Makefile
=> Fix: Dev dependencies are installed by default

readme.md
=> Enhancement: Use SVG badge for displaying Travis build status

phpunit.xml.dist
=> Enhancement: Use colors option when running phpunit

src/Faker/Guesser/Name.php, src/Faker/ORM/Doctrine/EntityPopulator.php, src/Faker/ORM/Propel/EntityPopulator.php
I kept finding dummy users with Lorem Ipsum as their salutation. This change uses the field length to be a bit more intelligent when that data is known. I've also tried to guess a few more column name and types.
=> Improve name guesser logic using field length when available

readme.md, src/Faker/Generator.php, src/Faker/Provider/Payment.php, src/Faker/Provider/hu_HU/Payment.php, src/Faker/Provider/ka_GE/Payment.php, src/Faker/Provider/no_NO/Payment.php, src/Faker/Provider/ro_MD/Payment.php, src/Faker/Provider/ro_RO/Payment.php, src/Faker/Provider/sv_SE/Payment.php, test/Faker/Provider/PaymentTest.php
Here I've:
* Added implementations of `bankAccountNumber` to all existing, supported locales
* Made made the `iban()` function public
* Allow `null` as the `$countryCode` (where it chooses a random, supported country)
* Added unit tests for all supported countries
This allows the explicit use of `iban()` for any locale and allows for the generation of IBANs from random countries.
The unit tests also warn (skip tests) about locales where bankAccountNumber is not implemented, even though an IBAN format is available. This currently warns about the "fake" locales at_AT and be_BE, which are deprecated in #594.
The one point I'm not sure on is the default value of iban($countryCode). I've set it to the current locale for IBAN countries and null (random) on the base class. For example, it would …
=> Expand IBAN interface

readme.md, src/Faker/Provider/Base.php, src/Faker/Provider/PhoneNumber.php, src/Faker/Provider/bn_BD/PhoneNumber.php, src/Faker/Provider/en_AU/PhoneNumber.php, src/Faker/Provider/en_NZ/PhoneNumber.php, src/Faker/Provider/en_US/PhoneNumber.php, src/Faker/Provider/pt_BR/PhoneNumber.php, src/Faker/Provider/ro_RO/PhoneNumber.php, src/Faker/Provider/vi_VN/PhoneNumber.php, src/Faker/Provider/zh_CN/PhoneNumber.php, test/Faker/Provider/BaseTest.php, test/Faker/Provider/en_US/PhoneNumberTest.php
This implements the rules for the North American Numbering Plan (NANP). It does not generate numbers including so-called "easily recognizable codes" which are used for various special services and not assigned to geographic regions, for example 911 (emergency), 411 (directory), 511 (traffic information) or 800 (toll-free).
Toll-free numbers can be generated with `tollFreePhoneNumber()`.
Fixes #588
=> US phone numbers

src/Faker/Provider/Color.php, test/Faker/Provider/ColorTest.php
I had to use this Faker data for a project. So I share this simple new functionality with the community :-)
=> Add RGBA functionality to Color Provider

src/Faker/Provider/Base.php
Hi, modified numberBetween() to be order agnostic (allow min/max to be supplied in either order).
I've done this as I found without this here, I had to put a *lot* of supporting conditional ordering code in my seeder script for a few specific usecases.  This makes using it much cleaner and won't break anything that currently uses it.
(And yes, am aware of randomFloat())
Thanks!
=> Modify numberBetween() to be order agnostic

src/Faker/Provider/Internet.php, test/Faker/Provider/InternetTest.php
Do not genate 255.255.255.255 (Broadcast) and IPs between 0.0.0.0 and 0.255.255.255 (0.0.0.0/8, current network).
https://en.wikipedia.org/wiki/IPv4#Special-use_addresses
> 0.0.0.0/8 	Current network (only valid as source address) 	RFC 6890
https://en.wikipedia.org/wiki/List_of_assigned_/8_IPv4_address_blocks
And 255.255.255.255 (Broadcast) must not be used, also.
````
16777216 = 1.0.0.0 (new lowest generatable IPv4)
-2 = 255.255.255.254 (new highest generatable IPv4)
````
=> Do not generate special purpose IPv4s

src/Faker/ORM/CakePHP/EntityPopulator.php
The return from the `primaryKey()` method can be both array and string, so this should be accounted for.
/cc @jadb
=> CakePHP ORM: Fix primaryKey warning

src/Faker/Provider/pt_BR/PhoneNumber.php
Currently a boolean is used to define if the cellphone should
contain the ninth digit or not. This was extended so if an area
code needs to be enforced, it can be generated externally and given
to the cellphone generator, and it will create a correct number.
> This wasn't made in the same branch as #622 since it's changing a method's argument, and it could create a little controversy. But in the end the behaviour is still backwards compatible :)
=> pt_BR: more flexibility to cellphone generation

src/Faker/Provider/Base.php, test/Faker/Provider/BaseTest.php
`Base::bothify()` now replaces an asterisk ('*') with either a random number or a random letter.
I also replaced `preg_replace_callback` in `numerify` and `lexify` as it is slower than iterating over a range of chars found by using `strpos` and `strrpos`.
Benchmarks are available here: https://gist.github.com/nineinchnick/84895a560910e3ead9cc
The biggest question is should we worry about UTF-8? I guess in a worst case it could replace the wrong byte. There are a few SO questions how to iterate over UTF-8 strings efficiently.
Should the new helper method `Base::replaceWildcard` be public?
=> Support an asterisk in bothify and optimize

src/Faker/Provider/en_AU/Address.php
Improves the $postcode options in the en_AU/Address.php Provider by restricting only to postcode that are valid.  Added because Faker was inserting invalid postcodes causing the application to not work correctly.
see https://en.wikipedia.org/wiki/Postcodes_in_Australia
=> Improve en_AU/Address $postcode

readme.md
Follow-up to #692.
I have chosen an example pointing out there may be several paragraphs. Though this occurs at a rate of about 2.5 %, I guess the newline might cause bad surprises if unexpected ;)
=> Fix result example of text()

src/Faker/DefaultGenerator.php, src/Faker/Provider/Address.php, src/Faker/Provider/Barcode.php, src/Faker/Provider/Base.php, src/Faker/Provider/Biased.php, src/Faker/Provider/Company.php, src/Faker/Provider/DateTime.php, src/Faker/Provider/File.php, src/Faker/Provider/Lorem.php, src/Faker/Provider/Miscellaneous.php, src/Faker/Provider/Person.php, src/Faker/Provider/PhoneNumber.php, src/Faker/Provider/Text.php, src/Faker/Provider/UserAgent.php, src/Faker/Provider/Uuid.php, src/Faker/Provider/lv_LV/Person.php
* shorten namespaces
* fix calling static methods as non static
* joins - implode change
=> minor update

src/Faker/Provider/Internet.php
Also fixes the missing lowercasing with the "no intl-ext" fallback.
Follow-up to #333 and #723.
=> Move lowercasing out of transliterate()

src/Faker/Provider/Internet.php
My apologies for the amount of PRs! (and there is one more to come after)
Something I forgot when moving from #723 to #725.
`transliterate()` result is surely ascii compatible[1]. And in any hypothetical worst-case scenario (like user messing low level), `mb_strtolower()` wouldn't fix anything anyways, but make upfront bug less noticeable.
The contract is clear: `transliterate()` result is ascii compatible. And with this commit we save 2 function calls each time, which is great.
[1] `return preg_replace('/[^A-Za-z0-9_.]/u', '', $transString);`
=> Optimize userName and domainWord

src/Faker/Factory.php
I guess it was needed before [c852326d](https://github.com/fzaninotto/Faker/commit/c852326dbd157ac700f896b2a6b73ac33014f783#diff-00672d0889830e234e31b675b5b493ee) (2011)?
=> Code simplification in Factory

src/Faker/ORM/CakePHP/Populator.php
Fixes a call to a missing method in the CakePHP ORM provider.
```php
$this->populator->addEntity('Articles', 50, $formatter, $modifier);
$this->populator->execute();  // Fatal error
```
=> Fix call to missing method typo

readme.md, src/Faker/Provider/Base.php, test/Faker/Provider/BaseTest.php
This PR if for #265.
I'm not 100% sure that the documentation is enough, let me know how to edit it if it isn't good.
Thanks
=> optional and boolean api inconsistency

src/Faker/Provider/nl_NL/Person.php
I changed the lastname `Jasper dr.` to `Jasper dr`. This lastname (with dot) does not occur anywhere in the Netherlands, plus it breaks the email generator. The email generator does not strip the last dot, so it can generate an email like this:  `Hassan.Jolijn@Jasperdr..net`.
This is, of course, an invalid email address according to PHP.
=> Remove an invalid Dutch lastname that breaks email generator

src/Faker/Calculator/Iban.php, src/Faker/Calculator/Luhn.php, src/Faker/DefaultGenerator.php, src/Faker/Documentor.php, src/Faker/Factory.php, src/Faker/Generator.php, src/Faker/Guesser/Name.php, src/Faker/ORM/CakePHP/ColumnTypeGuesser.php, src/Faker/ORM/CakePHP/EntityPopulator.php, src/Faker/ORM/CakePHP/Populator.php, src/Faker/ORM/Doctrine/ColumnTypeGuesser.php, src/Faker/ORM/Doctrine/EntityPopulator.php, src/Faker/ORM/Doctrine/Populator.php, src/Faker/ORM/Mandango/ColumnTypeGuesser.php, src/Faker/ORM/Mandango/EntityPopulator.php, src/Faker/ORM/Mandango/Populator.php, src/Faker/ORM/Propel/ColumnTypeGuesser.php, src/Faker/ORM/Propel/EntityPopulator.php, src/Faker/ORM/Propel/Populator.php, src/Faker/UniqueGenerator.php
Hi,
I added some PHPDocs and removed a unused variable.
greetings,
Daniel
=> added PHPDocs, removed unused variable

src/Faker/Provider/de_CH/Person.php, src/Faker/Provider/fr_CH/Person.php, src/Faker/Provider/it_CH/Person.php
Added first & last names for each Swiss region (`de_CH`, `fr_CH` and `it_CH`).
=> Add Swiss names

src/Faker/UniqueGenerator.php
Closes https://github.com/fzaninotto/Faker/issues/748
Since `$res` could be anything, it could also be an array or an object, so it must be serialized to be used for key checking.
=> Serialized `$res` key

src/Faker/Provider/cs_CZ/Person.php
Hello.
I added strict comparison to variable $gender in birthNumber method. This lowers bug risks and improves performance because in strict comparison the two pieces of data are being compared to have not only the same value, but the same type as well. This eliminates possible type-related bugs.
=> Added strict comparison to birthNumber method

src/Faker/Generator.php
Adding the $word property to method documentation to match actual method implementation.
=> Update imageUrl method documentation

readme.md, src/Faker/ORM/Spot/ColumnTypeGuesser.php, src/Faker/ORM/Spot/EntityPopulator.php, src/Faker/ORM/Spot/Populator.php
Adding [Spot2](https://github.com/vlucas/spot2) ORM support.
=> Add Spot ORM

src/Faker/Provider/zh_CN/PhoneNumber.php
- add: 178, 182, 183, 184 for china mobile;
- add: 175, 176 for china unicom;
- chg: remove redundant 145;
- add: 149, 177 for china telecom;
- add: 170, 171 for virtual operators.
=> update operators' phone number prefix.

src/Faker/Provider/Payment.php
=> Updated link to IBAN formats reference

readme.md, src/Faker/Provider/it_IT/Company.php, src/Faker/Provider/it_IT/Person.php, test/Faker/Provider/it_IT/CompanyTest.php, test/Faker/Provider/it_IT/PersonTest.php
Italian TaxId (Codice fiscale) https://it.wikipedia.org/wiki/Codice_fiscale
Italian VatId (Partita iva) https://it.wikipedia.org/wiki/Partita_iva
=> Italian Vat id and Tax id support

readme.md, src/Faker/Provider/pt_BR/Address.php
Brazilian region names and their abbreviations
=> Add region and region abbreviation methods

src/Faker/Provider/lv_LV/PhoneNumber.php
Phone numbers length for Latvia is 8 digits plus country code. And sometimes divided with spaces.
=> Latvia phone number format

src/Faker/Provider/Text.php
hi @fzaninotto !
I decided to push the changes requested in the issue https://github.com/fzaninotto/Faker/issues/527.
The code guidelines should be correct and tests passes.
Let me know if that is ok or should I update something.
best,
Javier
=> Text Provider ensure text starts with an uppercase letter #527

test/Faker/Provider/en_PH/AddressTest.php
Added unit test folder and AddressTest.php for ```en_PH``` Provider. 
Thank you.
=> Added en_PH unit test folder + AddressTest.php

src/Faker/Provider/en_ZA/Internet.php, test/Faker/Provider/en_ZA/InternetTest.php
Updated TLD list for South Africa locale and added Unit Test for Internet Provider
=> Updated TLD list for South Africa locale

readme.md, src/Faker/Provider/en_US/Payment.php, test/Faker/Provider/en_US/PaymentTest.php
This adds formatters for US account and routing numbers.
https://en.wikipedia.org/wiki/Routing_transit_number#MICR_Routing_number_format
=> Add en_US implementation for bank information

composer.json
This PR
:information_desk_person: The namespace is `Faker\Test`, not `Faker\PHPUnit`.
=> Fix: Namespace is Faker\Test, not Faker\PHPUnit

readme.md, src/Faker/Provider/Base.php, src/Faker/ValidGenerator.php, test/Faker/Provider/BaseTest.php, test/Faker/Provider/ColorTest.php
```php
<?php
// valid() only accepts valid values according to the passed validator functions
$values = array();
$evenValidator = function($digit) {
return $digit % 2 === 0;
};
for ($i=0; $i < 10; $i++) {
$values []= $faker->valid($evenValidator)->randomDigit;
}
print_r($values); // [0, 4, 8, 4, 2, 6, 0, 8, 8, 6]
// just like unique(), valid() throws an overflow exception when it can't generate a valid value
$values = array();
try {
$faker->valid($evenValidator)->randomElement(1, 3, 5, 7, 9);
} catch (\OverflowException $e) {
echo "Can't pick an even number in that set!";
}
```
Refs #567
=> [RFR] Introducting the valid() modifier

readme.md, src/Faker/Provider/Address.php, src/Faker/Provider/me_ME/Address.php, test/Faker/Provider/AddressTest.php, test/test.php
Sometimes you may want to set lat/lng parameters for a spesific area. 
Ex: 
For Istanbul:
'lat' => $faker->latitude(40.958836, 41.136456),
'lng' => $faker->longitude(28.64, 29.98),
=> min / max for lat long values

src/Faker/Provider/es_ES/Person.php, test/Faker/Provider/es_ES/PersonTest.php
I needed to generate DNI on unit tests and I use faker as data provider. I couldn't find DNI anywhere, so I implemented it
=> add DNI generator to spanis person

readme.md
Pomm is not a relational mapper.
=> Fix README’s improper definition

readme.md, src/Faker/Provider/PhoneNumber.php, src/Faker/UniqueGenerator.php, test/Faker/Provider/PhoneNumberTest.php
Added E.164 support as requested in issue #668
=> E.164 phone number generator

test/Faker/Provider/en_IN/AddressTest.php
Added unit test kit for file ```Address.php``` in ```en_IN``` provider.
The unit testing process goes as follows: 
1) Test that the variable is not empty
2) Test that internal type is string
3) Test that the string starts with upper-case letter (RegEx match)
Thank you.
=> Added en_IN unit test for Address.php

readme.md, src/Faker/Provider/Base.php
It was not clear for me whether randomElements() repeats input elements or not until I looked into the implementation.
=> docs: Clarify that randomElements() does not repeat input elements

src/Faker/Provider/en_AU/Address.php, test/Faker/Provider/en_AU/AddressTest.php
Hi. 
Looks like en_AU provider needed some attention. 
1) Added some provider methods for ```src/Faker/Provider/en_AU/Address.php``` file.
2) Created provider test class to ```test/Faker/Provider/en_AU/AddressTest.php```
3) Created test methods to ```test/Faker/Provider/en_AU/AddressTest.php``` in order to test that the results are sane.
Thank you.
=> Improved en_AU provider and added related unit tests

test/Faker/Provider/en_CA/AddressTest.php
Added ```test/Faker/Provider/en_CA/AddressTest.php``` unit test class to test ```en_CA``` provider. Unit test class tests province, province abbreviation and post code letters in three assertions: 
1) Variable is not empty
2) Variable type is a string 
3) Variable matches required RegEx pattern
Thank you.
=> Added unit testing for en_CA provider

test/Faker/Provider/ImageTest.php
Added ```curl``` check to file ```test/Faker/Provider/ImageTest.php``` to test LoremPixel before conducting the unit tests. 
Basically, this check utilises ```curl``` to retrieve HTTP header. If header includes response code which is between 200 and 299, unit tests are being conducted. Otherwise, they are skipped.
=> Added Lorempixel check for ImageTest.php

readme.md, src/Faker/Provider/nl_NL/Company.php, test/Faker/Provider/nl_NL/CompanyTest.php
The Dutch BTW number has the following:
- Countrycode **NL**
- 9 digit number 
- 3 character suffix (B01 to B99)
see [link (dutch)](http://www.belastingdienst.nl/wps/wcm/connect/bldcontentnl/belastingdienst/zakelijk/btw/administratie_bijhouden/btw_nummers_controleren/uw_btw_nummer) for more details
=> Added Dutch BTW (vat) Number

readme.md
The `Faker\Provider\pt_BR\Person` was wrong since `cnpj` isn't a valid Person attribute. Move it to `Faker\Provider\pt_BR\Company` provider and create it.
=> Improve README.me on pt_BR providers section

src/Faker/Provider/ru_RU/Text.php, src/Faker/Provider/uk_UA/Text.php
Removed ```@license``` from Text.php in both ```uk_UA``` and ```ru_RU``` locales. Since the texts are in public domain no license notice is required. 
This should be the last part of solution to ticket #881.
=> uk_UA & ru_RU: Removed @license from Text.php

src/Faker/Provider/de_DE/Person.php
Always include "Herr" or "Frau" in the title (formal salutation always includes the gender in German)
=> Improve german titles

src/Faker/Provider/el_GR/PhoneNumber.php
Source: https://en.wikipedia.org/wiki/Telephone_numbers_in_Greece
=> Add greek mobile and toll-free phone numbers

readme.md, src/Faker/Provider/DateTime.php, test/Faker/Provider/DateTimeTest.php
There are four `DateTime` returning methods: `dateTime`, `dateTimeAD`, `dateTimeBetween`, and `dateTimeInterval`,  Two of these (`dateTimeBetween` and `dateTimeInterval`) set the timezone on the returned object, while the other two do not.  This can lead to user land juggling timezones when comparing dates returned from the different generators.
This PR updates these four `DateTime` returning methods to set the time zone to result of `date_default_timezone_get` or the  user-specified timezone given in the final argument to all methods.  Test coverage updated to check that the default and custom time zones are handled.
=> Adds time zone support for provider methods returning DateTime instance

src/Faker/Provider/Base.php
=> Fix: Do not pick a random float less than minimum

Makefile
This PR
💁 It's faster, and it's also more in line with `.travis.yml`
=> Fix: Prefer dependencies installed from dist

src/Faker/Provider/de_AT/Address.php, src/Faker/Provider/de_CH/Address.php, src/Faker/Provider/de_DE/Address.php, test/Faker/Provider/en_SG/PhoneNumberTest.php
In Austria, Germany, and Switzerland a building number can have a letter as a suffix. Example: `Hauptstraße 23a`.
=> Add a building number with letter to German speaking locales.

src/Faker/Provider/Barcode.php
Fix eanChecksum function who check bad length for input. Correct sequence for ean8 checkSum is 3, 1 and not 1, 3. [See on Wikipedia](https://fr.wikipedia.org/wiki/EAN_8).
@fzaninotto Sorry for #950, it was a PR demo for web training session :smiley:
=> Fix EAN8 checkSum generator

src/Faker/Provider/DateTime.php, src/Faker/Provider/Internet.php
From Fedora QA, on 32bits
```
There were 2 errors:
1) Faker\Test\Provider\DateTimeTest::testDateTimeAD
mt_rand() expects parameter 1 to be integer, float given
/builddir/build/BUILDROOT/php-Faker-1.5.0-5.fc25.noarch/usr/share/php/Faker/Provider/DateTime.php:56
/builddir/build/BUILD/Faker-d0190b156bcca848d401fb80f31f504f37141c8d/test/Faker/Provider/DateTimeTest.php:27
2) Faker\Test\Provider\DateTimeTest::testFixedSeedWithMaximumTimestamp
mt_rand() expects parameter 1 to be integer, float given
/builddir/build/BUILDROOT/php-Faker-1.5.0-5.fc25.noarch/usr/share/php/Faker/Provider/DateTime.php:56
/builddir/build/BUILD/Faker-d0190b156bcca848d401fb80f31f504f37141c8d/test/Faker/Provider/DateTimeTest.php:83
```
=> fix 32bits issue

src/Faker/Provider/en_GB/Address.php, test/Faker/Provider/en_GB/AddressTest.php
Using `bothify` provides too many invalid post codes and the validator is too complex for `regexify` (attempts to chunk it failed)
Ended up adding 500 valid postcodes.
=> Adding valid en_GB postcodes

src/Faker/Provider/ja_JP/Text.php
In this PR, fix bug which call mb_substr() with invalid parameter in ja_JP Text.
error message when call $faker->realText:
`
mb_substr() expects parameter 3 to be integer, string given
`
=> Fix: fix invalid parameter of mb_substr()

src/Faker/Provider/is_IS/Person.php
Last names for females usually end in "dóttir", meaning "daughter".
Last names for males usually end in "son".
See: https://en.wikipedia.org/wiki/Icelandic_name#Typical_Icelandic_naming
=> Fix a mixup between male and female last names in Icelandic.

src/Faker/Provider/zh_CN/PhoneNumber.php
- remove 175 (illegal)
- according to https://en.wikipedia.org/wiki/Telephone_numbers_in_China
=> fix [zh_CN]PhoneNumber illegal operator prefix

readme.md
Adds [pattern-lab/plugin-php-faker](https://github.com/pattern-lab/plugin-php-faker) to the list; thanks!
=> Adding Pattern Lab plugin to list of 3rd party libraries

src/Faker/Provider/ja_JP/Text.php
fix mb_substr missing parameter error when generating japanese string with realText method
=> fix mb_substr missing parameter error when generating japanese string with realText method

src/Faker/Provider/pl_PL/Address.php, test/Faker/Provider/pl_PL/AddressTest.php
Added missing state handling in polish provider.
=> [pl_PL] Handle state.

.travis.yml, src/Faker/Generator.php, test/Faker/Provider/UuidTest.php
https://github.com/php/php-src/blob/php-7.1.0RC3/UPGRADING
=> [Generator.php] mt_rand() changed in PHP 7.1

src/Faker/Provider/nl_NL/Person.php
Removed some names that cannot occur or do not follow Dutch conventions, tweaked last name selector to far more accurately reflect the Dutch populace. Chance of selecting a 'noble' name reduced from 1:4 to 1:25, should be more like 1:25000 but it's good to generate them occasionally.
=> [nl_NL] Make person provider behave more realistically

src/Faker/Provider/Base.php, test/Faker/Provider/BaseTest.php
* "dice rolls" instead of "raffle tickets".
* can also be useful to pick more elements than the array length.
```php
$faker->randomElements(['foo', 'bar', 'baz', 'qux'], 3, true);
// possible result: 'foo', 'bar', 'foo'
```
=> Add allowDuplicates option to randomElements()

src/Faker/Provider/HtmlLorem.php, src/Faker/UniqueGenerator.php
In case of duplicate IDs the method fails.
Considering the small 5-digit-max range [0,99999] that's quite probable, and I [encountered it](https://travis-ci.org/fzaninotto/Faker/jobs/169501052#L282).
I did not increase the number of digits to be safe concerning BC.
A few notes about why I did the implementation as so:
* Doing `$this->unique()` or `$this->generator->unique()` would "pollute" (or be polluted by) the unique pool for `randomNumber` in other parts of the application.
* We want a fresh unique pool for each call to `randomHtml()`.
<br>ping @rudkjobing :)
=> Ensure unique IDs in randomHtml

.gitignore, src/Faker/Provider/en_ZA/Person.php
There was an extra ```$``` sign which caused the template to break. This has now been amended.  Fixes #1086.
Thank you.
=> Fixed Issue #1086

src/Faker/Provider/ko_KR/Address.php
Korean postal codes have been changed from the old xxx-xxx format to xxxxx on August 1, 2015
=> Change postal code format for ko_KR

src/Faker/Provider/ar_SA/Payment.php, src/Faker/Provider/at_AT/Payment.php, src/Faker/Provider/hr_HR/Payment.php, src/Faker/Provider/lt_LT/Payment.php
For locales:
- at_AT
- ar_SA
- hr_HR
- lt_LT
=> Add bankAccountNumber implementations

.gitignore, src/Faker/Provider/kk_KZ/Company.php, src/Faker/Provider/kk_KZ/Person.php, test/Faker/Provider/kk_KZ/CompanyTest.php, test/Faker/Provider/kk_KZ/PersonTest.php
=> kk_KZ Company/person identification numbers unit tests

src/Faker/Provider/Internet.php
This patch improves the performance of the `Internet::transliterate` method by not using the transliterator if the current string is already in ASCII.
It improves the speed of Alice's benchmark of 37%.
/cc @theofidry
=> Improve Internet::transliterate performance

readme.md
Hi. I created an adapter/Populator for Laravel's Eloquent ORM, but I released it as a [separate package](https://github.com/guidocella/eloquent-populator) because I ended up adding lots of stuff. So I added a link to it in the readme if it's ok. I don't know if I should add Eloquent to the list of supported ORMs.
=> Link Eloquent Populator

src/Faker/Calculator/Luhn.php
Hi.
Looks like class ```Faker\Provider\Base``` was declared in ```src/Faker/Calculator/Luhn.php``` but never used. Removed this dead code.
PHPUnit run before and after -- both passed. 
Thank you.
=> Removed dead code from Luhn.php

readme.md, src/Faker/Provider/DateTime.php, test/Faker/Provider/DateTimeTest.php
Introduced the ability to specify the timezone for the following methods:
* dateTimeThisCentury(),
* dateTimeThisDecade(),
* dateTimeThisYear(), and
* dateTimeThisMonth().
Updated readme and introduced new unit tests.
=> Introduced the ability to specify the timezone for dateTimeThis*() methods

src/Faker/Provider/pt_BR/PhoneNumber.php
Finally, every cellphone number on Brazil has 9 digits. We don't need to check its area anymore.
=> Updating ninth digit on whole country

src/Faker/Provider/en_IN/Address.php
Indian states added to en_IN locale
=> Indian states added to en_IN locale

readme.md, src/Faker/Provider/fr_FR/Person.php, test/Faker/Provider/fr_FR/PersonTest.php
File : `Faker\Provider\fr_FR\Person`
New function : `nir($gender = null, $formatted = false)`
Generates a NIR number.
=> Generates a random NIR number (fr_FR)

readme.md, src/Faker/Provider/zh_TW/Company.php, src/Faker/Provider/zh_TW/Person.php, test/Faker/Provider/zh_TW/CompanyTest.php, test/Faker/Provider/zh_TW/PersonTest.php, test/Faker/Provider/zh_TW/TextTest.php
Hi teams, thanks for the awesome faker features.
This PR includes.
- `VAT` in `zh_TW/Company`
- `personalIdentityNumber` in `zh_TW/Person`
- Tests
- Readme update
=> Add personal ID, VAT for zh_TW

src/Faker/Provider/Internet.php, test/Faker/Provider/InternetTest.php, test/Faker/Provider/ProviderOverrideTest.php
This change to prevent #935, without having to rely on specific fixes as in #936.
=> Remove trailing dot in username if any

src/Faker/Provider/nl_NL/Person.php
Based on: https://www.vernoeming.nl/alle-333-voorvoegsels-tussenvoegsels-in-nederlandse-achternamen
Fixed a few consistency issues along the way with handling single quotes.
Added the `prefix` method.
Due to the nature `$commonDutchLastNames` and `$dutchLastNames` are set up (already including the prefixes) I did not want to interfere with the current formats, but simply add additional functionality.
=> Add prefixes for nl_NL

.travis.yml, composer.json, src/Faker/Provider/Base.php
See https://wiki.php.net/rfc/deprecations_php_7_2#each
Also allowed using PHPUnit version 5 because version 4
also still uses the deprecated `each()` function. This
way the project will continue to build on future PHP
versions without sacreficing backwards compatibility to
PHP 5.3-5.5 versions. (Would be needed for allowing to
install PHPunit 6).
=> Rewrote deprecated `each()` usage

src/Faker/Calculator/Iban.php, src/Faker/Calculator/Luhn.php, src/Faker/DefaultGenerator.php, src/Faker/Generator.php, src/Faker/Provider/Barcode.php, src/Faker/Provider/Base.php, src/Faker/Provider/Biased.php, src/Faker/Provider/DateTime.php, src/Faker/Provider/HtmlLorem.php, src/Faker/Provider/Image.php, src/Faker/Provider/Internet.php, src/Faker/Provider/Text.php, src/Faker/Provider/UserAgent.php, src/Faker/UniqueGenerator.php, src/Faker/ValidGenerator.php
This PR removes unnecessary vars, fixes typos and adds missing doc block params
=> Typos and doc block fixes

readme.md, src/Faker/Provider/Miscellaneous.php, test/Faker/Provider/MiscellaneousTest.php
Added the ability to generate random Emoji.
These are Unicode characters from the block U+1F600 to U+1F637. 
Since many messages and text posts online now make use of Emoji (especially if send from a mobile device), I think some may find it useful.
=> Added Emoji to Miscellaneous

readme.md
It is documented in the phpdoc but not in the examples.
=> Add strict to randomNumber example

src/Faker/Provider/ru_RU/Person.php
This PR adds a method for middle name generation compatible (by signature) with `Person::firstName` and `Person::lastName`.
For details about the original problem see #1191
=> Add Person::middleName for ru_RU provider

src/Faker/Generator.php
=> Fix: Add class-level method annotations for DateTime provider

src/Faker/Provider/Image.php, test/Faker/Provider/ImageTest.php
Because https://lorempixel.com/ uses a valid SSL certificate, this will stop those pesky Mixed Content warnings.
In the good spirit of security, even while in development.
https://youtu.be/PdnpNJZVUE0
=> use secure https

src/Faker/Generator.php
=> Fix: Add method annotation for ValidGenerator

src/Faker/Provider/Text.php
Because `$textStartsWithUppercase` was always set to false no matter what you had set in localized class.
=> Use static instead of self

src/Faker/Provider/ka_GE/Text.php
There are no capital letters in Georgian.
=> Set capitals to false

src/Faker/Provider/uk_UA/Person.php, test/Faker/Provider/uk_UA/PersonTest.php
This is my first ever pull request. 
When generating Ukrainian names, only male middle names (patronymics) were used. For female names this did not correspond to the rules of the Ukrainian language. Added female middle names and test.
=> Corrected of grammar of Ukrainian middlenames and test added

readme.md, src/Faker/Generator.php, src/Faker/Provider/en_US/Person.php, test/Faker/Provider/en_US/PersonTest.php
This PR adds support for en_US social security numbers of the format: `AAA-GG-SSSS` (source: https://en.wikipedia.org/wiki/Social_Security_number#Structure).
SSN generation adheres to the following rules
- `AAA` must be between `001` and `899`, excluding `666`
- `GG` must be between `01` and `99`
- `SSSS` must be between `0001` and `9999`
=> Add compliant en_US SSN generator

.travis.yml
Travis-CI is moving towards Ubuntu Trusty for their default build environment, which doesn't support PHP 5.3 (so all PHP 5.3 builds fail for new contributors - see attached screenshot).
Since Faker requires PHP >= 5.3.3 – and thus should be tested on all PHP versions >= 5.3 – this PR locks the Travis-CI environment to Ubuntu Precise, which _does_ support PHP 5.3.
=> Lock Travis-CI environment to Ubuntu Precise

readme.md, src/Faker/Provider/nl_NL/Person.php, test/Faker/Provider/nl_NL/PersonTest.php
- Added personal identification number
=> Added idNumber for nl_NL

test/Faker/Provider/ImageTest.php
`http://lorempixel.com/` is being skipped because it responds with 301 instead of 200
`$url = "http://lorempixel.com/";   // line 48`
```
if ($httpCode < 200 | $httpCode > 300) {   // line 57
$this->markTestSkipped("LoremPixel is offline, skipping image download");
}
```
`test/Faker/Provider/ImageTest.php`
=> Fix CURL status code in ImageTest.php

readme.md
Fixed type-o in readme under section about Language specific formatters where it listed a language as no_NO not nb_NO.
=> Fixed type-o in readme under section about Language specific formatters

src/Faker/Provider/en_US/Person.php
suffix() uses late static binding, and no longer works when called from
an extending class. Another solution would be to use self instead of
static, but other properties in that class are protected too, so this
should make it look more consistent.
=> Allow children classes to access self::$suffix

readme.md, src/Faker/Provider/en_ZA/Person.php, test/Faker/Provider/en_ZA/PersonTest.php
Added licenceCode method in the en_ZA person provider, that generates a random valid South African licence code
=> South African licence codes

src/Faker/Provider/Image.php
When trying to unlink the file after unsuccessful download, a warning is thrown because file is still open
=> Fix "Resource temporarily unavailable"

src/Faker/Provider/en_ZA/Person.php, test/Faker/Provider/en_ZA/PersonTest.php
- The new titles are for Revenant (Rev.) and Honourable (Hon.)
- Remove unused use import for Faker\Provider\DateTime
=> Added male and female titles for the en_ZA locale

src/Faker/Provider/sl_SI/Company.php
Companies in Slovenija always have a suffix. Also, "and" is translated to "in".
=> [sl_SI] Created provider for Company

composer.json
As suggest in #1344 by @MarioBlazek, I  bump PHPUnit version to [`^4.8.35`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-4.8.md#4835---2017-02-06) and [`^5.7`](https://github.com/sebastianbergmann/phpunit/blob/master/ChangeLog-5.7.md#570---2016-12-02), that support that namespace.
=> Bump PHPUnit version for namespace compatibility

test/Faker/Provider/fi_FI/PersonTest.php
=> only test available date range on 32-bit

src/Faker/Provider/fr_FR/PhoneNumber.php, test/Faker/Provider/fr_FR/PhoneNumberTest.php
Bonjour François,
For the FR_fr provider, the `$faker->mobileNumber` does not call  the `phoneNumber07` and `phoneNumber07WithSeparator` methods because method `mobileNumber` does not invoke the generator but instead calls `static::numerify()` directly.
Also, not all of the 07xx formats have been transposed to `static::$mobileFormats`, and not all 07 formats call upon `phoneNumber07` or `phoneNumber07WithSeparator`, whereas they should.
I've shamelessly taken PR https://github.com/fzaninotto/Faker/pull/1304 from ctessier to fix the inners of the `mobileNumber()` method, and have replaced the `#` with `{{phoneNumber07[WithSeparator]}}` where approriate.
I've also added some tests (only tested the regular expressions, did not actually run the tests as I don't have PHPUnit installed).
Hoping …
=> Fix FR_fr 07 prefix mobile number generation

readme.md, src/Faker/Provider/nl_BE/Person.php, test/Faker/Provider/nl_BE/PersonTest.php
This will generate a Belgian social security number. I've added tests as well.
=> adds rijksregisternummer

test/Faker/Provider/UuidTest.php
According to your answer in
https://github.com/fzaninotto/Faker/issues/1346#issuecomment-343504794
=> skip test failing on bigendian

src/Faker/Provider/Payment.php
matching the function signature with the doc as defined in [`Faker\Generator`](https://github.com/fzaninotto/Faker/blob/9cda1a418ca4b2b71c9b921ebaea6c2e61e270b4/src/Faker/Generator.php#L48):
` @method string iban($countryCode = null, $prefix = '', $length = null)`
=> default value for Payment::iban() country code

src/Faker/Provider/Miscellaneous.php
This is an alternative approach to solve the issue described in #1360.
I removed SVC and ZWL from the list of currency codes.
While still in the list of official [ISO 4217 currency names](https://en.wikipedia.org/wiki/ISO_4217#Active_codes), these currencies are obsolete:
SVC has been replaced by the USD in 2001:
https://en.wikipedia.org/wiki/Salvadoran_col%C3%B3n
ZWL has been suspended since 2009:
https://en.wikipedia.org/wiki/Zimbabwean_dollar
Using them in Faker can cause 3rd party validations to fail.
=> Remove obsolete currency codes

test/Faker/DefaultGeneratorTest.php, test/Faker/GeneratorTest.php, test/Faker/Provider/BaseTest.php, test/Faker/Provider/DateTimeTest.php, test/Faker/Provider/PaymentTest.php, test/Faker/Provider/kk_KZ/PersonTest.php, test/Faker/Provider/nl_BE/PersonTest.php
I've refactored some tests, using:
- `assertInternalType` instead of `is_*` methods;
- `assertNull` and `assertNotNull` instead of strict comparisons with `null` keyword;
- `assertTrue` instead of strict comparisons with `true` keyword;
- `assertFalse` and `assertNotFalse` instead of strict comparisons with `false` keyword;
- `assertGreaterThan`, `assertGreaterThanOrEqual`, `assertLessThan` and `assertLessThanOrEqual` for mathematical comparisons;
- `assertSame` and `assertNotSame` instead of strict comparisons;
- `assertContains` instead of `in_array` method.
=> Refactoring tests

src/Faker/ORM/Propel/ColumnTypeGuesser.php, src/Faker/ORM/Propel2/ColumnTypeGuesser.php, src/Faker/ORM/Spot/EntityPopulator.php, src/Faker/Provider/es_VE/Person.php
I've removed the `else`s when we have already returned something :put_litter_in_its_place:
=> Clean elses

src/Faker/ORM/Doctrine/EntityPopulator.php
Use `is_callable` to prevent errors if a method is private.
=> Prevent errors on private methods

src/Faker/Provider/en_NZ/Internet.php
- Add .nz 1st level suffix
- Adds missing cri.nz 2nd level suffix
- Fix typos in parliament.nz and "New Zealand"
- Add link to .nz details
=> .nz domain updates

readme.md, src/Faker/Provider/es_ES/Person.php, test/Faker/Provider/es_ES/PersonTest.php
Added licenceCode method in the en_Es person provider, that generates a random valid Spain licence code
=> Add licenceCode method in the to es_ES person provider

src/Faker/Provider/Base.php, test/Faker/Provider/BaseTest.php
Often times when using Faker in our seeders, we will have Collection objects, not simple arrays. This PR allows the `randomElement()` and `randomElements()` methods to accept both arrays **and** objects that implement the `Traversable` interface.
rather than adding a bunch of conditionals to deal with arrays or objects, I decided to just normalize all Traversable objects to arrays at the start.  this lets the existing code operate as before.
=> allow `randomElements` to accept a Traversable object

src/Faker/Provider/Payment.php, test/Faker/Provider/PaymentTest.php
VISA retired the 13 digit PAN and 468 exist as of Dec 11, 2013. I have moved the retired card length into its own cardParams ("Visa Retired") to allow backward compatibility and allow the card length to still be generated if needed.
=> VISA retired the 13 digit PAN moved to new cardParams

src/Faker/ORM/Spot/EntityPopulator.php
In Spot2 you don't need to create getId methods for your entities and Faker requires from you to have such. Changing it like this will not force developer to create getId methods in Spot2 entity classes.
=> Fix for Spot2 ORM EntityPopulator

src/Faker/Provider/pt_BR/PhoneNumber.php
Implementation of the function that generates Brazilian area codes is fixed based on a list provided by the national organization that rules telecommunications.
Link to the resolution published in the ANATEL web site: http://www.anatel.gov.br/legislacao/resolucoes/16-2001/383-resolucao-263.
=> Implementation of the function that generates Brazilian area codes fixed.

src/Faker/Provider/el_GR/Company.php
Invalid character
The character `ο` is not equal to `o`   //  it seems the same
`'ο'`   ---to int->  206 // Not Letter
`'o'`   ---to int->  111   // Letter 'o'
=> Normalize name of variable

src/Faker/Provider/pl_PL/Person.php, test/Faker/Provider/pl_PL/PersonTest.php
Hi, polish PESEL faker has bug while generating PESEL for women.
10th digit in PESEL determines person sex. Even value mean woman, whether odd meas man. For now, tests sometimes fails, sometime passes. It's because of weird calculation using XOR.
This PR fixes this bug and add some tests to PESEL faker. In the past there were similar PR, but without tests: https://github.com/fzaninotto/Faker/pull/1037.
To run tests use this line: `phpunit --filter PersonTest test/Faker/Provider/pl_PL/PersonTest.php`
=> Fix Polish PESEL faker

src/Faker/Provider/kk_KZ/Person.php
According to documentations, when both checksum returns 10, Individual Identification Number cannot be used.
Example of such bad iin: Birth - 1989-04-02, Male, Population - 1584
=> Fixing rare iin with 13-digits.

test/Faker/Provider/DateTimeTest.php
There is a fixed date in the \Faker\Test\Provider\DateTimeTest::testFixedSeedWithMaximumTimestamp test that is set to 2018-03-01 12:00:00.
As this is now in the past it is causing the \Faker\Provider\DateTime::dateTimeThisMonth to throw an error which is causing the test to fail.
This increases the max date to 100 years in the future to avoid having to change this again, and allows the tests to pass once more
=> Push the max date far into the future so the test can pass

src/Faker/Provider/fr_CA/Address.php
Fixed the typo from Colombie-Brittanique to Colombie-Britannique
[source](https://en.wikipedia.org/wiki/British_Columbia)
=> Fix typo in fr_CA Provider

readme.md, src/Faker/Provider/fr_FR/PhoneNumber.php, test/Faker/Provider/fr_FR/PhoneNumberTest.php
As discussed in #1413. Added tests as well, updated readme.
=> Adds valid 08 number formats for fr_FR

src/Faker/Provider/hu_HU/Address.php
Reopened PR as @ppelgrims requested in https://github.com/fzaninotto/Faker/pull/1477#issuecomment-397215192
=> [hu_HU] Address: Fix unnecessary new line in string

src/Faker/ORM/Doctrine/EntityPopulator.php
There was a change made in #1363 to the `\Faker\ORM\Doctrine\EntityPopulator::fillColumns` method to prevent errors if the setter was a private method.
The `method_exists` call was changed to `is_callable`, but the parameters passed to the call were not updated which means it will always return false.
This updates them to check if the setter is callable.
Tests will pass if #1469 if merged in
=> Update the parameters to check if the setter is callable

src/Faker/Provider/it_IT/Company.php
SSIA.
Italy VAT Code should be:
- 7 number (random)
- 3 number (allowed values are city ISTAT code, that is a number between 1 and 121)
- Luhn control code
=> [it_IT] Improve vat ID generated using official rules

src/Faker/Provider/nl_NL/Person.php
When extending \Faker\Provider\nl_NL\Person $suffix cannot be used because it is private. Small fix to make it protected like the other properties.
=> Make $suffix protected not private

src/Faker/Provider/Base.php
Documentation says a-f, but code says a-c. Correcting documentation.
Fixes #1570
=> Correct documentation

src/Faker/Provider/nl_NL/Person.php
I saw my surname in the faked data, but it is misspelled. The misspelled version doesn't exist in The Netherlands.
=> Fix Dutch typo

src/Faker/Generator.php
I'm sorry for my poor English.
Faker\Provider\DateTime::dateTimeBetween() has $timezone argument.
But dateTimeBetween() on Generator phpdoc does not have this argument.
I added it.
=> Fix dateTimeBetween() Argument on Generator phpdoc

src/Faker/Generator.php
Without this patch, the `mt_rand` seed could stay at the very same
value, and so break all other usages to `mt_rand`.
---
Oh, We had really hard time to find this bug :)
We are using Faker in our test suite, and we get a really strange
behavior : some entity were generated with the exact same UUID.
ATM, our implement of UUID generation is based on `mt_rand`.
Anyway, we found that Faker modifies the seed and let it to the same
value. So with this patch, we restore the seed to a random value.
And eveything goes fine now.
=> Restore a random seed when the Generator is destroyed

.gitattributes
Hi,
Let's not publish all those file.
`.gitattributes` can be used to exclude files from final archive that is downloaded by composer.
We can test it locally by creating the `.gitattributes` files and running
git archive --format zip -o export.zip master command.
Read more
- https://madewithlove.be/gitattributes/
- https://alexbilbie.com/2012/11/exclude-objects-with-gitattributes/
- http://www.pixelite.co.nz/article/using-git-attributes-exclude-files-your-release/
=> Exclude files and folder from release archive

readme.md
https://www.php-fig.org/psr/psr-2/#54-for
=> PSR-2 updates to readme

src/Faker/Generator.php
added in #1493 - fixup the missing PHPDoc
from ![currently broken](https://i.imgur.com/cY9ZsbG.png)
to ![inspection working after](https://i.imgur.com/aAQ0rwR.png)
=> PHPDoc for `passthrough` function on Generator

src/Faker/Provider/en_CA/PhoneNumber.php
Everything else applies to Canada.
It may even be possible to remove the Canadian class, or remove everything in it to avoid a BC.
=> Make en_CA Phone Provider Extend the en_US One

readme.md
Just added a missing backslash in the populator example, to ensure consistency with the previous instruction.
=> Updated readme.md: added a missing backslash

readme.md, src/Faker/Provider/fa_IR/Person.php, test/Faker/Provider/fa_IR/PersonTest.php
I have updated the fa_IR Person Provider so as to add a main method and some helpers in order to enable the developer to generate valid national codes for fake Iranian Person instances.
=> Add Valid National Code Generator to fa_IR Person

readme.md
- PSR-0 has been marked as deprecated , PSR-4 is now recommended as an alternative. https://www.php-fig.org/psr/psr-0/
- the ClassLoader component entirely is no longer maintained. https://github.com/symfony/class-loader
=> Suggest PSR-4 compliant autoloader in comment

.travis.yml, src/Faker/Provider/Base.php, src/Faker/Provider/Internet.php, src/Faker/Provider/Lorem.php, src/Faker/Provider/ar_JO/Company.php, src/Faker/Provider/ar_SA/Company.php, src/Faker/Provider/en_US/Company.php, src/Faker/Provider/es_AR/Company.php, src/Faker/Provider/es_ES/Company.php, src/Faker/Provider/es_PE/Company.php, src/Faker/Provider/fi_FI/Company.php, src/Faker/Provider/hy_AM/Company.php, src/Faker/Provider/it_IT/Company.php, src/Faker/Provider/ru_RU/Company.php, src/Faker/Provider/sk_SK/Company.php
For PHP 7.4 the implode methods will break:
`implode(): Passing glue string after array is deprecated. Swap the parameters`
I also updated travis to match 7.3. However there is no 7.4 env available in Travis yet as far as i know
=> PHP 7.4 compatibility

src/Faker/Provider/en_NG/Person.php
Fixed a little typo, from "Isreal" to "Israel".
=> Fix-Isreal--Israel

src/Faker/Provider/Image.php
LoremPixel offers a grayscale option which was already available in the `imageUrl` method in the Image provider; however, this option was missing in the`image` method.
=> Added missing grayscale option/flag to Image provider

CONTRIBUTING.md, Makefile, composer.json, src/Faker/ORM/Spot/EntityPopulator.php, src/Faker/Provider/Base.php, src/Faker/Provider/HtmlLorem.php, src/Faker/Provider/en_US/Payment.php, src/Faker/Provider/ka_GE/Company.php, src/Faker/Provider/mn_MN/Person.php, src/Faker/Provider/ms_MY/Address.php, src/Faker/Provider/ms_MY/Company.php, src/Faker/Provider/ms_MY/Miscellaneous.php, src/Faker/Provider/ms_MY/Payment.php, src/Faker/Provider/ms_MY/Person.php, src/Faker/Provider/ms_MY/PhoneNumber.php, src/Faker/Provider/nb_NO/Person.php, src/Faker/Provider/nl_NL/Company.php, src/Faker/Provider/nl_NL/Person.php
This PR
💁‍♂ For reference, see https://github.com/squizlabs/PHP_CodeSniffer/compare/1.5.6...2.9.2.
=> Enhancement: Update squizlabs/php_codesniffer

readme.md, test/Faker/Provider/ImageTest.php
This PR
Somewhat related to #1714.
=> Enhancement: Assert that imageUrl can be used with gray flag

.travis.yml
This PR
Somewhat related to #1758, as 3rd-party extensions (such as Xdebug) are not installed on nightly builds (see https://docs.travis-ci.com/user/languages/php/#nightly-builds).
=> Fix: Allow nightly builds to fail

src/Faker/Provider/de_AT/Address.php
Temp fix for https://github.com/fzaninotto/Faker/issues/1544 - should probably implement more strict values in the future
=> fix austrian postal codes starting with invalid 0

Makefile
=> Enhancement: Introduce build and help targets

.travis.yml
This PR
💁‍♂ We currently don't need it, and this potentially speeds up builds. For reference, see https://docs.travis-ci.com/user/languages/php/#disabling-preinstalled-php-extensions.
=> Enhancement: Disable Xdebug as early as possible

readme.md
This PR
💁‍♂ I'd also suggest 
- consistently liking to GitHub repositories (rather than in at least one example, linking to https://packagist.org)
- perhaps removing abandoned packages
- splitting the list (perhaps into sections _Framework Integrations_ and _Providers_)
- keeping the list(s) sorted by package name
We could also start adding GitHub issue and pull request templates, and add a template for adding a library that gives suggestions, what do you think?
=> Enhancement: Consistently use composer package name for link content

test/Faker/Provider/de_AT/AddressTest.php
=> Enhancement: Assert that postcode generated by Austrian Address provider matches format

src/Faker/ORM/CakePHP/ColumnTypeGuesser.php
This will avoid deprecation warnings by accessing `getColumn` if the method exists. Otherwise access the old `column` method.
Solve #1616
=> FIx: Avoid deprecation warning in newer CakePHP version

readme.md, src/Faker/Provider/Color.php, test/Faker/Provider/ColorTest.php
This will add `hslColor` and `hslColorAsArray` for `ColorProvider`
Closes #1720
=> Add hslColor to ColorProvider

readme.md
Added some more info about autoloading since there are some questions as issues on this. Since 99% of the people will install the package via composer anyways i think its more easy
=> Added some more information for autoloading in the readme

readme.md
The word **Licence** is written in french. It should be written in english to keep consistency with the other occurrences of the word in this document.
=> Minor typo fix

readme.md
=> Fix: Consistently link to GitHub repositories

src/Faker/Provider/nl_NL/Company.php
Previously generated company names only consisted of one or two surnames and a suffix. This resulted in unrealistic and sometimes extremely long company names like "de la Fontaine und d’Harnoncourt Unverzagt Mohan EESV" and "Martena van Burmania Vegilin van Claerbergen".
The new faker generates realistic company names like "Fietsenmaker Zijlemans" and "Elektronicakampioen BV".
=> Improve Dutch company names

readme.md, src/Faker/ORM/Doctrine/Populator.php
Added a counter a batch size to insert in batches instead of all at once on which doctrine orm will block itself due the fact it holds all in memory.
Works fine and it reduces the memory consumption a lot. The smaller the batches the less memory it will consume but will be less fast as well.
Only problem that still remains is the return of the PKs inserted though. I don't think there is a real solution for that when you want to keep track of so much data. Did a test with 100k records for this though meaning it holds 100k PKs in an array.
=> Added batch inserts for doctrine orm populate

src/Faker/Provider/ru_RU/Person.php, test/Faker/Provider/ru_RU/PersonTest.php
Add` lastName` method on **Person Provider** ru_RU locale with gender params.
Related to #1745.
=> Add lastName gender specific on ru_RU locale

src/Faker/Provider/Internet.php
Autoloading breaks in Yii 1 applications when checking if the `Transliterator` class exist.
I disabled autoloading in the call to `class_exists`
=> Prevent Transliterator class autoloading

src/Faker/Provider/zh_TW/Person.php
Every citizen has a unique ID number. A valid National Identification number consists of one letter and nine-digits. The initial letter depends on the place of one's first household registration. 
https://en.wikipedia.org/wiki/National_Identification_Card_(Republic_of_China)
=> Taiwan ID. The initial letter must be a capital letter. p->P

src/Faker/Provider/id_ID/Color.php
i add some color for id_ID provider
=> add id_ID Color

src/Faker/Provider/en_SG/PhoneNumber.php, test/Faker/Provider/en_SG/PhoneNumberTest.php
Singapore mobile number only starts with 8 or 9. Not 7. The 2nd digit is never a 9 as well
See: http://en.wikipedia.org/wiki/Telephone_numbers_in_Singapore#Numbering_plan
Hope it helps!
```
8zxx xxxx - Mobile and Data Services
9yxx xxxx - Mobile, Data Services and Pager (until May 2012)
Which also means:
8[1-8]xx xxxx - Mobile and Data Services
9[0-8]xx xxxx - Mobile, Data Services and Pager (until May 2012)
x denotes 0 to 9
y denotes 0 to 8 only
z denotes 1 to 8 only
```
=> Bug Fix en_SG mobile number generation

src/Faker/Provider/Company.php, src/Faker/Provider/nl_NL/Company.php
This PR
Follows #1529.
💁‍♂ Probably best reviewed commit by commit.
=> Enhancement: Slightly clean up Company provider

src/Faker/Provider/Miscellaneous.php
This pull request replaces the following obsolete currency codes with their new equivalents:
MRO -> MRU
STD -> STN
VEF -> VES
Data taken from wikipedia https://en.wikipedia.org/wiki/ISO_4217#Historical_currency_codes
=> Update out-of-date currency codes

src/Faker/Provider/nl_NL/Person.php
Title method is not static so it raises a php strict warning
=> Calling a non static method as static not allowed.

src/Faker/Provider/pt_PT/Company.php, src/Faker/Provider/pt_PT/Internet.php
Added the most common terminology for portugueses companies, the most common free mail domains and top level domains.
=> Portuguese providers for Companies and Internet

readme.md
The method name in the en_NZ provider should be mobileNumber instead of cellNumber.
=> Fix method name for en_NZ provider in readme

src/Faker/Calculator/Luhn.php, test/Faker/Provider/fi_FI/PersonTest.php, test/Faker/Provider/sv_SE/PersonTest.php
Curly braces for arrays is deprecated in PHP 7.4 (detected by PHPCompatibility)
=> Curly braces for arrays is deprecated in PHP 7.4

Makefile, phpunit.xml.dist
=> Enhancement: Configure verbose output via phpunit.xml.dist

.gitignore, .travis.yml, .travis/xdebug.sh, Makefile, phpunit.xml.dist, readme.md
=> Enhancement: Collect code coverage

CHANGELOG.md
=> Added changelog for the 1.9.1 release

readme.md
=> Fix: Aggregate badges in one place

.travis.yml
=> Fix: Run build against PHP 7.4

Makefile, composer.json
=> Fix: Configure preferred installation method via composer.json

.github/workflows/continuous-integration.yml
=> Fix: Use extensions key instead of deprecated extension-csv

.github/workflows/continuous-integration.yml
This PR
Follows #1890.
💁‍♂ It's a lot faster!
=> Enhancement: Collect code coverage using pcov

src/Faker/Generator.php
=> Enhancement: Add type and return type declarations to Generator

psalm.xml
This PR
Follows #1897.
💁‍♂ The idea is to raise the error level one by one and fix issues as we encounter them.
=> Enhancement: Require error level 7

phpcs.xml
This PR
Follows #1896.
💁‍♂ Helps with auto-completion!
=> Enhancement: Reference schema for phpcs configuration

.github/workflows/continuous-integration.yml, Makefile
This PR
Running
```
$ make sniff
```
yields
```
vendor/bin/phpcs
............................................................  60 / 574 (10%)
............................................................ 120 / 574 (21%)
............................................................ 180 / 574 (31%)
............................................................ 240 / 574 (42%)
............................................................ 300 / 574 (52%)
............................................................ 360 / 574 (63%)
............................................................ 420 / 574 (73%)
............................................................ 480 / 574 (84%)
............................................................ 540 / 574 (94%)
.................................. …
```
=> Enhancement: Use cache for squizlabs/php_codesniffer

phpcs.xml
=> Enhancement: Use colors when running phpcbf or phpcs

src/Faker/ORM/Doctrine/Populator.php
Bug: https://github.com/fzaninotto/Faker/issues/1862
Clear specific entities is deprecated and will not be supported in Doctrine 3.0. (https://github.com/doctrine/orm/commit/9ccb8837e7f0bc605117024561c07e487a57eca0)
Bug introduced: c49cd5438655043b487f4d986961746ae58edb3a
Related issue: https://stackoverflow.com/questions/18215975/doctrine-a-new-entity-was-found-through-the-relationship
=> Fix (bug #1862): Do not clear entity manager for doctrine orm populator

readme.md
- Add `countryISOAlpha3` to the readme
- Fix `locale` and `countryCode` examples (`en_UK` and `UK` are not valid)
=> Add countryISOAlpha3 to documentation

src/Faker/Provider/DateTime.php, test/Faker/Provider/DateTimeTest.php
Fix dateTimeThisYear method in issue #2027
I referred to this document.
https://www.php.net/manual/en/datetime.formats.relative.php#122278
Thank you.
=> Fix dateTimeThisYear method

src/Faker/Provider/ru_RU/Person.php, test/Faker/Provider/ru_RU/PersonTest.php
Now female lastname generated from male lastname (in cyrillic) and adding latin letter 'a', so female lastname contains as cyrillic as latin letters. It cause errors in validating rules, for example. 
This fix just changes latin 'a' to cyrillic 'а'
=> Fix letter 'a' in female lastname generation (ru_RU)

.github/dependabot.yaml
This PR
💁‍♂️ All of the pull requests that we now manually open can be automated. To be honest, it feels like years ago that I manually updated dependencies. In the @ergebnis organization, I even let GitHub Actions automatically merge pull requests created by Dependabot, given that the build passes.
=> Enhancement: Add configuration for Dependabot

psalm.xml, src/Faker/Factory.php, src/Faker/Guesser/Name.php, src/Faker/Provider/File.php
=> Enhancement: Raise error level from 6 to 5

composer.json, composer.lock
This PR
❗ Blocks #2063.
💁‍♂️ For reference, see https://github.com/slevomat/coding-standard/compare/6.1.5...6.4.1.
=> Enhancement: Update slevomat/coding-standard

phpcs.xml, src/Faker/Provider/ms_MY/Address.php, src/Faker/Provider/ms_MY/Person.php, test/Faker/Provider/BaseTest.php, test/Faker/Provider/nl_BE/PersonTest.php
=> Enhancement: Enable UnusedUses rule

composer.json, composer.lock, psalm.xml
This PR
❗ Blocks #2063.
💁‍♂️ On one hand, `psalm/plugin-phpunit` depends on `phpunit/phpunit`, and on the other hand, `symfony/phpunit-bridge` conflicts with `phpunit/phpunit`. If we want to use `symfony/phpunit-bridge`, we need to remove `psalm/plugin-phpunit`.
=> Fix: Remove psalm/plugin-phpunit

.gitattributes, .github/workflows/continuous-integration.yml, .phive/phars.xml, Makefile, composer.json, composer.lock
This PR
❗ Blocks #2063.
💁‍♂️ This allows us to escape dependency hell: `vimeo/psalm:^3.18.2` has at least one dependency, i.e., `webmozart/glob`,  that does not support PHP 8.0 yet.
For reference, see:
- https://github.com/vimeo/psalm/blob/3.18.2/composer.json#L37
- https://github.com/webmozart/glob/blob/4.1.0/composer.json#L12
👉 Note that I am checking in [`.phive/psalm`](https://github.com/fzaninotto/Faker/pull/2088/files#diff-38b8c466eaddc15f8224c6637c02e110c365735374b48a6c6547236ca0b21187), so contributors do not have to install `phive`.
=> Enhancement: Use vimeo/psalm as PHAR
