fzaninotto/Faker

- readme.md
- src/Faker/Provider/be_BE/Payment.php
- test/Faker/Provider/be_BE/PaymentTest.php
> +1 per-country VAT number, for be_BE

- readme.md
- src/Faker/Provider/bg_BG/Payment.php
- test/Faker/Provider/bg_BG/PaymentTest.php
> +1 per-country VAT number, for bg_BG

- readme.md
> add faker Behat context to third party library section of readme

- src/Faker/Provider/it_IT/Text.php
Added Dante Alighieri's Inferno to the italian text provider
> Adding it_IT Text Provider

- src/Faker/ORM/CakePHP/EntityPopulator.php
Happens when a TestFixture uses Faker but associated models (fixtures) do not (or have no
records seeded yet).
> Fix cases where no entities prev. inserted

- src/Faker/Provider/nl_NL/Address.php
- src/Faker/Provider/nl_NL/Person.php
Because the name created in #559 seems really weird, it being a title is more logical.
> It's supposed to be a title after a last name

- src/Faker/Provider/es_PE/Person.php
http://es.thefreedictionary.com/Srta.
http://es.thefreedictionary.com/Dra.
> Typo Srita. doesn't exist

- readme.md
- src/Faker/Provider/Image.php
- test/Faker/Provider/ImageTest.php
> Custom text on the picture

- src/Faker/Provider/hu_HU/Text.php
> hu_HU sample text

- .travis.yml
> Enhancement: Cache dependencies installed with Composer between builds

- composer.json
> move intl extension to require-dev in composer.json file

- src/Faker/ORM/Doctrine/EntityPopulator.php
> mt_rand instead of rand()

- src/Faker/Provider/lv_LV/Color.php
- src/Faker/Provider/lv_LV/Person.php
+ add Color provider
* fix static method calling in Person provider
> Update for Latvian language

- src/Faker/Calculator/Iban.php
- src/Faker/Documentor.php
- src/Faker/ORM/CakePHP/EntityPopulator.php
- src/Faker/ORM/Propel/ColumnTypeGuesser.php
- src/autoload.php
+ add return annotation
* remove unused local vars.
> fix few phpmd notices

- readme.md
Hello,
After your refusal of the imagesGenerator directly inside Faker ( fzaninotto#712 ), I updated it as an external provider as you suggested me to.
Here is the documentation update for the new provider link.
Best regards!
> Added images-generator as third party

- test/Faker/Provider/fi_FI/InternetTest.php
Hi all.
Finnish language Faker was missing unit tests so I decided to start creating some.
Thank you.
> Finnish unit tests added

- test/Faker/Provider/ar_SA/InternetTest.php
Unit test folder added for ar_SA provider. 
Thank you.
> ar_SA unit test folder added

- test/Faker/Provider/bn_BD/PersonTest.php
Unit test folder added to bn_BD provider with PersonTest.php test class. 
Thank you.
> Added bn_BD unit test folder + PersonTest.php

- readme.md
- src/Faker/Provider/en_ZA/Address.php
- src/Faker/Provider/en_ZA/Company.php
- src/Faker/Provider/en_ZA/Person.php
- src/Faker/Provider/en_ZA/PhoneNumber.php
- test/Faker/Provider/en_ZA/CompanyTest.php
* Added an en_ZA company provider, that can generate company registration numbers
> * Added an en_ZA company provider, that can generate company registration numbers

- test/Faker/Provider/de_DE/InternetTest.php
Added unit test folder for de_DE provider + InternetTest.php. 
Thank you.
> Added de_DE unit test folder

- test/Faker/Provider/da_DK/InternetTest.php
Added dk_DK unit test folder with InternetTest.php to increase test coverage. 
Thank you.
> da_DK Provider unit test added

- src/Faker/Provider/en_IN/Address.php
- src/Faker/Provider/en_IN/Internet.php
- src/Faker/Provider/en_IN/Person.php
- src/Faker/Provider/en_IN/PhoneNumber.php
Added provider for Indian data. Contains Address, Person, Phone number and Internet data.
> Added provider for en_IN (India)

- src/Faker/Provider/Image.php
Add ability to generate gray images by providing "true" as the final parameter to imageUrl().
> Update Image.php to allow generation of gray images using lorempixel

- src/Faker/ORM/Spot/EntityPopulator.php
Good afternoon.
I switched loose boolean comparison to strict boolean comparison in line 126 to lower bug risk and improve performance of guessColumnFormatters method.
Thank you.
> Switched to strict comparison on src/Faker/ORM/Spot/EntityPopulator.php

- src/Faker/ORM/Spot/ColumnTypeGuesser.php
I can do the same changes for Doctrine, BUT it will change values for existing seeds (randomFloat has different functionality than it's there now).
Given that Spot provider is new, I think we can afford changes here. 
So, what do you think about Doctrine?
> Use generator to populate values for numeric fields for Spot provider.

- src/Faker/Provider/de_CH/PhoneNumber.php
- src/Faker/Provider/fr_CH/PhoneNumber.php
- src/Faker/Provider/it_CH/PhoneNumber.php
- test/Faker/Provider/de_CH/PhoneNumberTest.php
- test/Faker/Provider/fr_CH/PhoneNumberTest.php
- test/Faker/Provider/it_CH/PhoneNumberTest.php
Fixed the wrong international prefix and added valid mobile number formats.
> Improve Swiss phone numbers

- test/Faker/Provider/en_UG/AddressTest.php
Added unit test folder for en_UG provider and AddressTest.php. 
Thank you.
> Added unit test folder for en_UG provider and AddressTest.php

- test/Faker/Provider/en_NZ/PhoneNumberTest.php
Implemented unit test folder for en_NZ provider and PhoneNumberTest.php test file. All PHPUnit tests passed locally.
Thank you.
> Added en_NZ unit test folder + PhoneNumberTest.php

- test/Faker/Provider/en_CA/PhoneNumberTest.php
Unit test support added to en_CA Provider, with PhoneNumberTest.php test kit. 
Thank you.
> en_CA unit test folder added

- test/Faker/Provider/en_AU/PhoneNumberTest.php
Added en_AU unit test folder. 
Thank you.
> Added en_AU unit test folder

- readme.md
- src/Faker/Provider/en_ZA/PhoneNumber.php
- test/Faker/Provider/en_ZA/PhoneNumberTest.php
* Updated Phone Number Provider for the en_ZA locale to provide more accurate numbers
* Added mobile phone and special rates number functions
> * Updated Phone Number Provider for the en_ZA locale

- test/Faker/Provider/ar_JO/InternetTest.php
/test/Faker/Provider/ar_JO unit test folder added to improve code coverage.
Thank you.
> Added ar_JO unit test folder + InternetTest.php

- readme.md
Fix modifiers link in readme.md.
> Fix modifiers link in readme.md

- src/Faker/Provider/nl_NL/Text.php
> Add nl_NL base text

- readme.md
- src/Faker/Generator.php
> Add boolean property notes

- src/Faker/Provider/zh_TW/Text.php
Removed  a function from loop in file ```src/Faker/Provider/zh_TW/Text.php```. In order to avoid the overhead of executing the function multiple times, I made a change to pre-calculate it before the loop begins. This increases efficiency. Thank you.
> Removed function from loop in zh_TW provider

- src/Faker/Provider/fa_IR/Internet.php
> Add more IR TLD

- src/Faker/Provider/nb_NO/Address.php
- src/Faker/Provider/nb_NO/Company.php
- src/Faker/Provider/nb_NO/Payment.php
- src/Faker/Provider/nb_NO/Person.php
- src/Faker/Provider/nb_NO/PhoneNumber.php
> [RFR] Rename norwegian locale

- src/Faker/Generator.php
No code change, just add doc for IDE auto-complete
> Add phpdoc method dateTimeInInterval in Generator.php

- src/Faker/Provider/ro_RO/Text.php
Same text as in previous PR but this time with proof of public domain copyright and source.
> Adding Text for ro_RO

- src/Faker/Provider/en_GB/Address.php
- src/Faker/Provider/en_IN/Address.php
- src/Faker/Provider/en_US/Address.php
- src/Faker/Provider/lv_LV/Address.php
- src/Faker/Provider/ne_NP/Address.php
- src/Faker/Provider/vi_VN/Address.php
> #989 Fix country typo

- readme.md
- src/Faker/Provider/ar_SA/Payment.php
- src/Faker/Provider/he_IL/Payment.php
- src/Faker/Provider/hr_HR/Payment.php
- src/Faker/Provider/lt_LT/Payment.php
I updated the new IBAN locales, so that `bankAccountNumber` is available.
> IBAN Formatters for New Locales

- src/Faker/Provider/es_VE/Person.php
Add Numbers of Nationalized Citizens in Person.php
Correct EOL Windows to Unix and adapting code a PSR-2
> Adding Nationalized Citizens to DNI in Person.php

- src/Faker/Provider/pl_PL/Text.php
Fixed '--' to ' - '. Before this `słońca--lśniące` was treated as one word.
> Fixed polish text - change '--' into '-'.

- src/Faker/Provider/fr_FR/PhoneNumber.php
Refs https://github.com/fzaninotto/Faker/pull/167#issuecomment-250761730
> Fix French phone numbers with 07 prefix

- src/Faker/Provider/PhoneNumber.php
Make first digit of E164 number a not null number
> Issue #1041

- src/Faker/Provider/fi_FI/PhoneNumber.php
With this patch, generated phone numbers are more realistic.
It's also easier to improve the formats in the future, if needed.
> [fi_FI] Improve phone number generator

- src/Faker/Provider/en_ZA/Person.php
- test/Faker/Provider/en_ZA/PersonTest.php
Added id number generator to Person Provider for the en_ZA locale
Added simple provider id number method unit test
> Added id number generator to Person Provider for the en_ZA locale

- src/Faker/Generator.php
Improves the usability in IDE's like PHPStorm
> Docblocks: Add some missing @method tags

- readme.md
Fixed the default locale stated in the readme for Faker\Factory
> (Minor) Fixed the default locale stated in the readme

- src/Faker/Generator.php
> Update method signature in Generator phpdoc

- readme.md
- src/Faker/Provider/ja_JP/Person.php
- test/Faker/Provider/ja_JP/PersonTest.php
Changed person name for ja_JP
Updated README.md for ja_JP
I divided Japanese kana name by gender.
> [ja_JP]kana of Japanese name by gender.

- readme.md
Just adding Eloquent to the list of supported ORMs.
Refs #1120
> Say Eloquent is supported

- src/Faker/Provider/Payment.php
Fix unused code in the Payment class
> Fix unused code

- readme.md
- src/Faker/Provider/es_PE/Person.php
- test/Faker/Provider/es_PE/PersonTest.php
Adds a Peruvian Document Nacional de Identidad number generator to new locale es_ES.
> Add Peruvian DNI generator

- readme.md
- src/Faker/Provider/en_NG/Address.php
- src/Faker/Provider/en_NG/Internet.php
- src/Faker/Provider/en_NG/Person.php
- src/Faker/Provider/en_NG/PhoneNumber.php
- test/Faker/Provider/en_NG/AddressTest.php
- test/Faker/Provider/en_NG/InternetTest.php
- test/Faker/Provider/en_NG/PersonTest.php
- test/Faker/Provider/en_NG/PhoneNumberTest.php
Localization for Nigeria should be en_NG #1171 Renamed classes and created a readme entry
> Fix ng_NG to en_NG

- src/Faker/Provider/sv_SE/Company.php
Added list of Swedish (sv_SE) job titles.
> Add swedish job titles

- composer.json
Update the Composer file: bumped the branch alias and added consistent version constraints.
This way way we can test the new version by requiring the `^1.7` development version.
> Update Composer File

- src/Faker/Provider/Miscellaneous.php
> Update ISO 4217 active codes

- src/Faker/Provider/ja_JP/Internet.php
- test/Faker/Provider/ja_JP/InternetTest.php
Unified Internet and Person format.
Because the internet class format is small and there are many duplications.
> Add Internet Format for ja_JP.

- readme.md
- src/Faker/Provider/es_VE/Company.php
- src/Faker/Provider/es_VE/Person.php
- test/Faker/Provider/es_VE/CompanyTest.php
- test/Faker/Provider/es_VE/PersonTest.php
New function to generate tax ids for companies and the option to have a format for those ids.
> Tax Id for companies and new formats for es_VE

- src/Faker/Provider/ru_RU/Text.php
> Fix #1305 realText in some cases breaks last character

- readme.md
> Added link in readme to provider FakerRestaurant

- src/Faker/Provider/fr_FR/Company.php
- src/Faker/Provider/fr_FR/Payment.php
- test/Faker/Provider/fr_FR/PaymentTest.php
Fixes issue #1342, added missing tests as well.
> French vat formatter

- src/Faker/Provider/th_TH/PhoneNumber.php
update new Thailand (th_TH) mobile number format
- 06x xxx xxxx
- 06 xxxx xxxx
> update th_TH mobile number format

- src/Faker/Provider/Text.php
- test/Faker/Provider/el_GR/TextTest.php
- test/Faker/Provider/fr_FR/TextTest.php
- test/Faker/Provider/ka_GE/TextTest.php
- test/Faker/Provider/kk_KZ/TextTest.php
- test/Faker/Provider/ko_KR/TextTest.php
- test/Faker/Provider/ru_RU/TextTest.php
As discussed in #1378, tests were added as well
> Replaces rtrim with preg_replace

- readme.md
- src/Faker/Provider/ms_MY/Address.php
- src/Faker/Provider/ms_MY/Company.php
- src/Faker/Provider/ms_MY/Miscellaneous.php
- src/Faker/Provider/ms_MY/Payment.php
- src/Faker/Provider/ms_MY/Person.php
- src/Faker/Provider/ms_MY/PhoneNumber.php
- test/Faker/Provider/ms_MY/PersonTest.php
Added Malaysia [ms_MY] locale provider for Address, Company, Miscellaneous, Payment, Person, and PhoneNumber.
> added Malaysia [ms_MY] locale

- src/Faker/Generator.php
- src/Faker/Provider/DateTime.php
Should fix #1418.
I've gone over all the methods in the DateTime provider to make sure they were accurate.
> Update PHPDoc of the DateTime provider.

- readme.md
Add link to the [aalaap/faker-youtube](https://github.com/aalaap/faker-youtube) provider.
> Add YouTube provider link

- readme.md
Full disclosure: I'm the creator of this provider. I hope someone finds it useful.
> Add fake-car provider link

- readme.md
> Add PicsumPhotos Provider to the thrid parties

- src/Faker/Generator.php
Make `e164PhoneNumber` and `e164PhoneNumber` available to IDEs
> Update doc block

- readme.md
I have written a loremflickr.com provider, since lorempixel works slow or gets down.
> Add loremflickr.com Provider to the thrid parties

- test/Faker/Provider/en_NG/PhoneNumberTest.php
Added declaration for the Faker Generator instance in the PhoneNumber test
> Add Undeclared Faker Instance to PhoneNumber Test in en_NG

- src/Faker/Provider/fr_CA/Text.php
Text from Project Gutenberg EBook
La chasse galerie, by Honoré Beaugrand.
Thanks
> Added realText capability for fr_CA

- .gitattributes
> Enhancement: Clean up .gitattributes

- readme.md
Hi,
I just released [drupol/belgian-national-number-faker](https://packagist.org/packages/drupol/belgian-national-number-faker) and I'm submitting a PR to include it in the README.
Thanks.
> Update README - Add a new faker.

- readme.md
This PR
Follows #1770.
🤦‍♂ Sorry!
> Fix: Name of package

- src/Faker/Provider/Color.php
> Revert "Added 'red' to $safeColorNames"

- .github/ISSUE_TEMPLATE/bug.md
> Enhancement: Add issue template for bug report

- readme.md
- src/Faker/Provider/nb_NO/PhoneNumber.php
- test/Faker/Provider/nb_NO/PhoneNumberTest.php
Added `$faker->mobileNumber` for Norwegian mobile phone numbers.
Included tests for the method, and added docs to the readme.md about this. Tests are currently passing.
> Add mobileNumber() method for nb_NO

- readme.md
- src/Faker/Generator.php
Adds missing documentation for the randomDigitNot base formatter.
> Document randomDigitNot base formatter.

- src/Faker/Provider/Biased.php
Floor is not always returning an int:
https://www.php.net/floor
> Floor is not always returning an int

- src/Faker/Provider/id_ID/Internet.php
> add .id TLD

- src/Faker/Provider/pt_BR/Payment.php
Lista de bancos brasileiros adicionados para ser gerado aleatóriamente.
> List of banks in Brazil added

- src/Faker/Provider/fa_IR/PhoneNumber.php
Add all of Iran's provinces land lines number formats separated by province name.
> Add all Iran's provinces land lines numbers

- readme.md
As discussed here #1794 I created my own repo with Gravatar provider. 
Could you add the link, please? Maybe it will be useful to someone else too
> Add link to Gravatar provider repository

- .travis.yml
- composer.json
> Fix: Require PHP 7.2

- src/Faker/Provider/en_NG/Person.php
- test/Faker/Provider/ProviderOverrideTest.php
- test/Faker/Provider/es_VE/CompanyTest.php
- test/Faker/Provider/es_VE/PersonTest.php
> Fix: Remove unnecessary class-level DocBlocks

- phpunit.xml.dist
> Enhancement: Use all columns when running tests

- .github/workflows/continuous-integration.yml
This PR
Related to #1847.
💁‍♂ Let's see if this even works.
> Enhancement: Echo a greeting

- .github/workflows/continuous-integration.yml
> Fix: Invoke composer directly

- .gitattributes
- .github/workflows/continuous-integration.yml
- Makefile
- phpcs.xml
> Enhancement: Use XML configuration for squizlabs/php_codesniffer

- CHANGELOG.md
> Enhancement: Add note about 'Keep a Changelog'

- readme.md
> Fix: Show build status for next branch

- .github/workflows/continuous-integration.yml
> Enhancement: Synchronize workflow

- src/Faker/Calculator/Luhn.php
- test/Faker/Provider/fi_FI/PersonTest.php
- test/Faker/Provider/sv_SE/PersonTest.php
See https://wiki.php.net/rfc/deprecate_curly_braces_array_access
> Fix: Remove deprecated curly braces

- .gitattributes
- .github/workflows/continuous-integration.yml
- Makefile
- composer.json
- psalm-baseline.xml
- psalm.xml
- readme.md
- src/Faker/Provider/Base.php
- src/Faker/Provider/cs_CZ/Person.php
- src/Faker/Provider/is_IS/Address.php
- src/Faker/Provider/me_ME/Payment.php
- src/Faker/Provider/pl_PL/Person.php
- test/Faker/Provider/de_CH/AddressTest.php
- test/Faker/Provider/de_CH/InternetTest.php
- test/Faker/Provider/de_CH/PhoneNumberTest.php
- test/Faker/Provider/en_AU/AddressTest.php
- test/Faker/Provider/en_CA/AddressTest.php
- test/Faker/Provider/en_IN/AddressTest.php
- test/Faker/Provider/en_NZ/PhoneNumberTest.php
- test/Faker/Provider/en_PH/AddressTest.php
- test/Faker/Provider/en_UG/AddressTest.php
- test/Faker/Provider/fr_CH/AddressTest.php
- test/Faker/Provider/fr_CH/InternetTest.php
- test/Faker/Provider/fr_CH/PhoneNumberTest.php
- test/Faker/Provider/fr_FR/AddressTest.php
- test/Faker/Provider/it_CH/AddressTest.php
- test/Faker/Provider/it_CH/InternetTest.php
- test/Faker/Provider/it_CH/PhoneNumberTest.php
- test/Faker/Provider/pt_PT/PersonTest.php
> Enhancement: Run a static code analysis and collect type coverage with vimeo/psalm

- composer.lock
This PR
💁‍♂ Running
```
$ composer validate
```
on current `next` yields
```
The lock file is not up to date with the latest changes in composer.json, it is recommended that you run `composer update` or `composer update <package name>`.
./composer.json is valid
```
> Fix: Update composer.lock

- phpcs.xml
> Enhancement: Show progress when running phpcbf or phpcs

- composer.json
- composer.lock
- phpcs.xml
- src/Faker/Provider/Base.php
- src/Faker/Provider/ms_MY/Person.php
- test/Faker/Provider/BaseTest.php
- test/Faker/Provider/BiasedTest.php
- test/Faker/Provider/PersonTest.php
- test/Faker/Provider/PhoneNumberTest.php
- test/Faker/Provider/TextTest.php
- test/Faker/Provider/ar_JO/InternetTest.php
- test/Faker/Provider/ar_SA/InternetTest.php
- test/Faker/Provider/da_DK/InternetTest.php
- test/Faker/Provider/de_AT/InternetTest.php
- test/Faker/Provider/de_CH/InternetTest.php
- test/Faker/Provider/de_DE/InternetTest.php
- test/Faker/Provider/en_NG/InternetTest.php
- test/Faker/Provider/en_US/CompanyTest.php
- test/Faker/Provider/en_US/PersonTest.php
- test/Faker/Provider/en_ZA/InternetTest.php
- test/Faker/Provider/en_ZA/PersonTest.php
- test/Faker/Provider/fa_IR/PersonTest.php
- test/Faker/Provider/fi_FI/InternetTest.php
- test/Faker/Provider/fr_CH/InternetTest.php
- test/Faker/Provider/fr_FR/CompanyTest.php
- test/Faker/Provider/it_CH/InternetTest.php
- test/Faker/Provider/nl_BE/PersonTest.php
- test/Faker/Provider/tr_TR/CompanyTest.php
- test/Faker/Provider/tr_TR/PersonTest.php
> Enhancement: Enable AlphabeticallySortedUses rule

- src/Faker/Generator.php
See (https://github.com/fzaninotto/Faker#fakerprovideren_uscompany)
> Added missing properties in doc-block

- src/Faker/Provider/de_DE/Company.php
Was missing a simple letter 😊 thanks for this awesome library 👍
> Fix typo in de_DE jobTitleFormat

- test/Faker/Provider/HtmlLoremTest.php
- test/Faker/Provider/de_CH/AddressTest.php
- test/Faker/Provider/fr_CH/AddressTest.php
- test/Faker/Provider/it_CH/AddressTest.php
I refactored some methods which were not psr-2 compliant.
Please review.
> [refactor] complies with psr-2

- .github/workflows/continuous-integration.yml
> Enhancement: Update actions/checkout

- .github/workflows/continuous-integration.yml
> Enhancement: Update actions/cache

- composer.json
- composer.lock
- psalm-baseline.xml
This PR
💁‍♂️ For reference, see https://github.com/vimeo/psalm/releases/tag/3.18.2.
> Enhancement: Update vimeo/psalm

- composer.json
- composer.lock
This PR
❗ Blocks #2063.
💁‍♂️ For reference, see https://github.com/Dealerdirect/phpcodesniffer-composer-installer/compare/v0.6.2...v0.7.0.
> Enhancement: Update dealerdirect/phpcodesniffer-composer-installer

- readme.md
> Fix: PHP requirement in README.md
